name: Solarman MQTT Bridge
version: "1.0.0"
slug: solarman
description: "Bridge between Solarman PV inverter and Home Assistant via MQTT."
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
panel_icon: mdi:solar-power
options:
  mqtt_broker: "mqtt://homeassistant.local"
  mqtt_username: ""
  mqtt_password: ""
  solarman_sn: ""
schema:
  mqtt_broker: str
  mqtt_username: str
  mqtt_password: password
  solarman_sn: str
image: ""